name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Sample Azure action
        with: # Set Azure credentials secret as an input
          credentials: ${{ secrets.SECRET }}
        env: # Or as an environment variable
          credentials: ${{ secrets.NEWSECRET }}
