name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
  steps:
    - name: Sample Azure action
      with: # Set Azure credentials secret as an input
        credentials: ${{ secrets.SECRET }}
      env: # Or as an environment variable
        credentials: ${{ secrets.NEWSECRET }}
