name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: sample action
        with:
          credentials: ${{ secrets.SECRET }}
        env:
          credentials: ${{ secrets.NEWSECRET }}
      - run: echo "🎉 printed secrets event."
      
     
